### PR TITLE
81 fault priority

### LINKED ISSUE #81: [FAULTS] - Implement fault priority & non critical fault capability
### Current Features

We currently have a set of faults that all (as required by rules) cause the car to turn off with equal authority. 

### Desired Additional Features

There are some things that can go wrong that aren’t critical, but would be nice to know. Right now, we just dont really track these. We want to add non critical fault capability and perhaps fault tiers, so that we have a framework for tracking other things that go wrong, that we dont want to actually turn the car off. 

Ideally, these would exist within the current fault framework, and wed simple add a parameter that defined severity level, with only the highest producing the shutdown behavior we currently have. But, there are different approaches to this architecture, and there may be others that fit well too.

As a sort of “test case” there is currently one error that we catch and do nothing with that fits this bill - CAN errors. In the can handler, you will find a TODO that points to turning this into a non-critical fault. While implementing the faults is mostly out of scope of this ticket, try adding that one as proof of concept 

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by tszwinglitw**
## Changes

- added `is_critical` field in fault_eval_t 
- separate critical from non-critical faults in `acc_data_t`
- moved bms fault status to a a standalone can message + can send function

## To Do
- create non-critical faults

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please reach out to your Project Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No merge conflicts
- [x] All checks passing
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #81

### CODE REVIEW

File: Core/Src/stateMachine.c [hunk 1]
```diff
@@ -251,80 +268,100 @@ uint32_t sm_fault_return(acc_data_t *accData)
...
+			}
+		}
 		incr++;
 	}
-	// TODO: Remove This !!!!
-	fault_status &= ~DISCHARGE_LIMIT_ENFORCEMENT_FAULT;
-	return fault_status;
+
+	// TODO: Remove This !!!! (because this is actually a non-critical fault?)
+	// fault_status &= ~DISCHARGE_LIMIT_ENFORCEMENT_FAULT;
```
Comment (jr1221) [inline Core/Src/stateMachine.c:290]: @Sabramz hmmm should this be here or not

**Review by jr1221 — COMMENTED** [review]
Wait for @Sabramz review

File: Core/Src/stateMachine.c (hunk 1 above)
Comment (Sabramz) [reply Core/Src/stateMachine.c:290]: I do not know. Something tells me this was a debugging thing done in a rush last year. Lets bring DCL fault back in, and if it gives us problems we can remove it easily.

**Review by Sabramz — APPROVED** [review]
I really like these changes.
